### ISSUE TITLE
IHP_BASEURL and IHP_IDE_BASEURL set wrong if you open Codespaces in VS Code

### ISSUE THREAD

**Issue by CSchank** [rvarun11/codespaces-ihp#1]
When using Codespaces inside VS Code instead of in the browser, you need to run the following to start the server and have it work properly:

`IHP_BASEURL="http://127.0.0.1:8000" IHP_IDE_BASEURL="http://127.
0.0.1:8001" ./start`

Otherwise, IHP will try to redirect to the Codespaces URLs which don't work when running inside VS Code.

I'm not sure if we can somehow fix this. Maybe there is an API Codespaces provides to tell us if it's running in VS Code or on the web. Or maybe we just need to add something to the Readme so people know they should type the command above to override the Codespaces URLs.

**Comment by rvarun11** [comment]
Fixed in: d8bb05e
